### ISSUE TITLE
MakeFile for Windows

### ISSUE THREAD

**Issue by dewang** [mwbrooks/cordova-plugin-menu#21]
The make file for the project is currently supported for Linux platform only. We would like to have a Make file that works in Windows platform as well so that we can do any modifications if required.

**Comment by mwbrooks** [comment]
Hi @dewang,

The Makefile should work fine on both Linux and Windows. It may possibly work on Windows running cygwin (Unix shell) with Make installed.

The Makefile is simply intended to speed up my own development of the plugin. However, adding compatibility to Windows is time consuming, especially if it's only for potential future modifications.

**Comment by dewang** [comment]
Thanks for your feedback,

I am trying to run the make file using NMake, which is windows equivalent of Make. The reason we want Make file is to be able to compile and enhance the menus in case we need to do any changes later down the line. This one is lower in priority at the moment, but we would like to be able to build the menus from our development environment.

**Comment by mwbrooks** [comment]
A while back, I wrote documentation ton [building the Makefile with Windows](https://github.com/nitobi/phonegap-plugin-menu/blob/master/doc/getting-started/android.md). I do not use NMake and instead I use a Unix terminal within Windows.

**Comment by dewang** [comment]
Hi Michael,

Thanks for the update. I have now been able to use your make file to build the commited code. You can close this issue now.

**Comment by mwbrooks** [comment]
Awesome to hear!
