### ISSUE TITLE
Use Common PhoneGap.exec

### ISSUE THREAD

**Issue by mwbrooks** [mwbrooks/cordova-plugin-menu#24]
If possible, it would be nice if iOS can use the universal `PhoneGap.exec` interface. I'm not sure where this is at for iOS, but I cannot find any "core" APIs using the interface.

For example, instead of:

```
PhoneGap.exec("NativeControls2.updateToolBarItem", data['data-uuid'], { 'label': data['label'] });
```

use

```
PhoneGap.exec(
    successCallback,
    failCallback,
    "com.phonegap.menu.toolbar",
    "label",
    [ data["label"] ]
);
```

**Comment by shazron** [comment]
Fixed in https://github.com/nitobi/phonegap-plugin-menu/pull/26

**Comment by mwbrooks** [comment]
Commit 036e26408b3f84b00d30fbd548f31ac279b56298
