### ISSUE TITLE
Menu on iOS is taking too long to display when application is loaded for the first time

### ISSUE THREAD

**Issue by dewang** [mwbrooks/cordova-plugin-menu#30]
We are trying the sample application that contains a native menu contro. We have noticed that the menu appears a few seconds after the application is loaded. This is more pronounced when the application is run for the first time. Can you please fix it so that the behaviour is similar to that of Android, which loads up almost instantly

**Comment by mwbrooks** [comment]
I agree. I'll be meeting with Shazron tomorrow to discuss options to increase the rendering time.
