### ISSUE TITLE
Android Menu Item has TypeError

### ISSUE THREAD

**Issue by infil00p** [mwbrooks/cordova-plugin-menu#34]
Tried to use the MenuPlugin.  The menu appears, but when I select the menu, I get this error below:

E/Web Console( 6728): Uncaught TypeError: Cannot read property 'elements' of undefined at :1

This is most likely related to the fact that the Menu tag doesn't work properly on Android, since there are markup errors.  Currently have this issue with the version of PhoneGap that is bundled with the current plugin.

**Comment by mwbrooks** [comment]
Can you please provide a code sample of where you create the menu or a GitHub link to the line number.

**Comment by infil00p** [comment]
Here's the relevant commit: https://github.com/nitobi/Clairmail/commit/730ebb70a8b8e3818f9a6ddadcbd7348837b9265
