### ISSUE TITLE
Unable to use this plugin

### ISSUE THREAD

**Issue by rkumar670** [mwbrooks/cordova-plugin-menu#39]
Hi Mwbrooks, 
I am unable to use you plugin. All stuffs are in different folders not in the android project.
May you help me how to you use your plugin may you give the working example.
waiting for you reply,

thanks,
rahul kumar
rkumar670@gmail.com

**Comment by mwbrooks** [comment]
Hi @rkumar670,

Unfortunately, this plugin is incredibly out of date and will not work with the latest version of Cordova/PhoneGap.

I still think this could be a useful plugin to developers, but I currently don't have the free-time to actively develop it. If you're interested in helping out, then I'd be down for collaborating.

Michael

**Comment by rkumar670** [comment]
ya Michael I am interested to help you...

skype:rkumar670
