### ISSUE TITLE
How should I use this plugin

### ISSUE THREAD

**Issue by pjnovas** [mwbrooks/cordova-plugin-menu#43]
Hey there!, The readme is awesome, but can you add an example of use?, I really don't understand how to use it, where is the source or compiled, or a .js file to import?

Which versions of cordova are supported?, I've just downloaded v 2.2 is it working on that one?

Sorry, maybe its me, I've never used a plugin for phonegap before, is it embeded on the library?

Thanks!

**Comment by pjnovas** [comment]
Oh, I've checked out the closed issues and it's not a mantanied anymore, too sad :( 

If you're looking for people to help contact me, I'm interested on this

Thanks anyway!

**Comment by devgeeks** [comment]
It's being rebuilt. 

But work has only barely begun.
